Issue9 create auth
rubyforgood/justice pull request #18
Opened 2017-05-19 19:06 UTC by almightyboz

* Add Devise to gemfile, configure env/development.rb
* Create users table, add names and roles
* Add Devise views

2017-05-19 19:13 UTC, jmkoni approved these changes
👍

2017-05-19 19:49 UTC, osondoar commented on app/views/layouts/application.html.erb
> +	<p class="notice"><%= notice %></p>
`application.html.erb` is going to probably be the layout for the public site. The flash message should only be needed in the layout for the internal site (which we don't have yet). I think we can remove those flash messages for now.

2017-05-19 19:58 UTC, osondoar commented on config/environments/development.rb
> +  config.action_mailer.default_url_options = { :host => 'justice.dev' }
The host refers to the mail server. I would leave it to `config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }` in development.

Btw, this tool is great for testing emails locally: https://mailcatcher.me/

2017-05-19 19:59 UTC, osondoar commented on test/models/user_test.rb
> +require 'test_helper'
This looks like a mini test spec. Can you make it a rspec one?

2017-05-19 20:02 UTC, osondoar commented
Just added a couple comments, but 👍 overall.

2017-05-20 00:06 UTC, iamanissa reviewed
for the schema, do we want usernames, or just name?

2017-05-20 12:58 UTC, jmkoni requested changes
Right now, there are also a lot of commits in this PR that aren't yours. Usually that means a rebase went haywire.

2017-05-20 13:23 UTC, closed without merging

2017-05-20 13:32 UTC, almightyboz commented on app/views/layouts/application.html.erb
> +	<p class="notice"><%= notice %></p>
A note, Devise requested that we have those in for flash messages after login/logout. I'll put them in the internal site when we have it.