Style calendar item page
rubyforgood/justice pull request #81
Opened 2017-07-17 03:04 UTC by AliTopal89

the new create page
<img width="541" alt="screen shot 2017-07-16 at 10 54 41 pm" src="https://user-images.githubusercontent.com/9599485/28254382-4b761ef2-6a7a-11e7-927b-95796320bcf3.png">

the new edit page 
<img width="1003" alt="screen shot 2017-07-16 at 10 53 59 pm" src="https://user-images.githubusercontent.com/9599485/28254377-33b6d36a-6a7a-11e7-940f-56d977307d53.png">

the new edit page with datepicker
<img width="926" alt="screen shot 2017-07-16 at 10 54 13 pm" src="https://user-images.githubusercontent.com/9599485/28254342-d76af55a-6a79-11e7-99de-e2ccd5b79f64.png">

the new show page 
<img width="423" alt="screen shot 2017-07-16 at 10 59 14 pm" src="https://user-images.githubusercontent.com/9599485/28254392-6ff2c9ce-6a7a-11e7-9556-d391731059b4.png">

the edit page was too close to the header therefore added `margin-top:30px` seems responsive

wanted the buttons to align nicely with the rest of the form made changes in custom.scss

2017-07-18 04:04 UTC, osondoar commented
Thanks for the contribution!

I was trying to figure out why the calendar views were off and It looks like at some point we lost part of the original css for the calendar view in `custom.scss`, probably because of merge conflicts. I've restored some of that style as part of #82 . That PR fixed the `edit` view, but not the `new` view.

Can you rebase  your branch and resubmit the PR?

A few comments:
- The form in the view and edit pages can be defined just once in a partial (`_form.html.erb`). Take a look at the [terms views](https://github.com/rubyforgood/justice/tree/master/app/views/admin/terms) to see how you can reuse it the form across views. You should use the html in `edit.html.erb` and discard the form html in `new.html.erb`. 
That new partial can also contain the JS `Pikaday` definition, so we define it just once.

- With the new changes, using the `form-group` is no longer neccesary.

- The submit buttons currently say "Create Calendar" and "Update Calendar", can you update them to "Create Event" and "Edit Event"?

2017-07-18 04:24 UTC, osondoar requested changes

2017-07-18 04:24 UTC, osondoar commented on app/views/admin/calendar_items/edit.html.erb
> +<script>
we can move this to a `_form.html.erb` partial

2017-07-18 04:24 UTC, osondoar commented on app/views/admin/calendar_items/edit.html.erb
>       <%= form_for([:admin, @calendar_item]) do |f| %>
The form definition would also be part of the partial

2017-07-18 04:24 UTC, osondoar commented on app/views/admin/calendar_items/edit.html.erb
> +           <dd><%= f.text_field :title, class: "form-control" %></dd>
I believe that after you rebase, `form-control` is no longer neccesary

2017-07-18 04:33 UTC, osondoar requested changes

2017-07-18 04:33 UTC, osondoar commented on app/views/admin/calendar_items/edit.html.erb
> +       <%= f.submit "Update Calendar", class: " btn btn-primary", id: "custom-edit", style: "margin-top: 10px" %>
Let's rename "Update Calendar" to "Save Event"

2017-07-18 04:33 UTC, osondoar commented on app/views/admin/calendar_items/new.html.erb
>    <%= f.submit "Create Calendar", class: "btn btn-primary" %>
Let's rename "Create Calendar" to "Save Event"

2017-07-19 16:18 UTC, AliTopal89 commented
Will look at these later today or tomorrow and I'll resubmit a pull request for sure. Thank you for your feedback. 👍

2017-07-24 04:12 UTC, closed without merging